<?php
/**
 * @return array
 * implement hook_schema()
 * creates the entity base table in the database
 *
 */
function commerce_fulfillment_schema() {

  $schema = array();

  $schema['commerce_fulfillment_packages'] = array(
    'description' => 'The base table for the package entity',
    'fields' => array(
      'package_id' => array(
        'description' => 'Primary key of the package entity',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'order_id' => array(
        'type' => 'varchar',
        'length' => '255',
        'not null'=> TRUE,
      ),
      'box_type' => array(
        'type' => 'varchar',
        'length' => '255',
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('package_id'),
  );

  $schema['commerce_fulfillment_shipments'] = array(
    'description' => 'The base table for the Shipment entity',
    'fields' => array(
      'shipment_id' => array(
        'description' => 'Primary key of the Shipment entity',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'order_id' => array(
        'type' => 'varchar',
        'length' => '255',
        'not null'=> TRUE,
      ),
      'status' => array(
        'description' => 'Status of the shipment("Pending" or "Completed")',
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
      ),
      'tracking_number' => array(
        'description' => 'Tracking number for the shipments',
        'type' => 'varchar',
        'length' => '255',
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('shipment_id'),
  );

  return $schema;

}

/**
 * implements hook hook_uninstall
 * clears global variables
 *
 */
function commerce_fulfillment_uninstall(){
  variable_del('commerce_fulfillment_package_type');
  variable_del('commerce_fulfillment_company');
  variable_del('commerce_fulfillment_address');
  variable_del('commerce_fulfillment_phone');
  variable_del('commerce_fulfillment_boxtype');
  variable_del('commerce_fulfillment_logo');
  drupal_flush_all_caches();
}
