<?php
/***********************************************************************************
 * This file is part of Comerce Fulfilment. A drupal module used to fulfil         *
 * orders placed in the Drupal Commerce module.                                    *
 *                                                                                 *
 * Authors: Dylan Harvey, Evan Schisler, Levi Weir, Parker Groenewoud              *
 *                                                                                 *
 * Project for COSC224 - Projects in Computer Science at Okanagan College.         *
 * Sponsored by AcroMedia                                                          *
 *                                                                                 *
 *                                                                                 *
 * Version: 1.0 - 12/03/15 - (Code before header)                                  *
 *          1.1 - 26/03/15 - (Code after header)                                   *
 *          1.2 - 08/04/15 - (Added additional fields to the shipment entity.)     *
 * Originially from: http://choosealicense.com/licenses/mit/                       *
 * The MIT License (MIT)                                                           *
 *                                                                                 *
 *                                                                                 *
 *                                                                                 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy    *
 * of this software and associated documentation files (the "Software"), to deal   *
 * in the Software without restriction, including without limitation the rights    *
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       *
 * copies of the Software, and to permit persons to whom the Software is           *
 * furnished to do so, subject to the following conditions:                        *
 *                                                                                 *
 * The above copyright notice and this permission notice shall be included in all  *
 * copies or substantial portions of the Software.                                 *
 *                                                                                 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      *
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        *
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     *
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          *
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   *
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   *
 * SOFTWARE.                                                                       *
 **********************************************************************************/
/**
 * @return array
 * implement hook_schema()
 * creates the entity base table in the database
 *
 */
function commerce_fulfilment_schema() {

    $schema = array();
    /**
     * package entity
     *
     */
    $schema['commerce_fulfilment_packages'] = array(
        'description' => 'The base table for the package entity',
        'fields' => array(
            'package_id' => array(
                'description' => 'Primary key of the package entity',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'order_id' => array(
                'type' => 'blob',
                'not null'=> TRUE,
            ),
            'line_items' => array (
                'type' => 'blob',
                'serialize' => TRUE,
                'not null' => FALSE,
	        ),
	        'box_type' => array(
                'type' => 'varchar',
                'length' => '255',
                'not null' => FALSE,
            ),
	        'shipping_info' => array(
                'type' => 'blob',
                'serialize'=> TRUE,
                'not null' => TRUE,
            ),
        ),
            'primary key' => array('package_id'),
        );
    /**
     * shipment entity
     */
        $schema['commerce_fulfilment_shipments'] = array(
            'description' => 'The base table for the Shipment entity',
            'fields' => array(
                'shipment_id' => array(
                    'description' => 'Primary key of the Shipment entity',
                    'type' => 'serial',
                    'unsigned' => TRUE,
                    'not null' => TRUE,
                ),
                'status' => array(
                    'description' => 'Status of the shipment("Pending" or "Completed")',
                    'type' => 'varchar',
                    'length' => 255,
                    'not null' => TRUE,
                ),
                'packages' => array(
                    'description' => 'An array of the packages in the shipment.',
                    'type' => 'blob',
                    'serialize' => TRUE,
                    'not null' => FALSE,
                ),
                'date' => array(
                    'description' => 'Date the shipment was shipped',
                    'type' => 'int',
                    'length' => 8,
                    'not null' => FALSE,
                ),
                'method' => array(
                    'description' => 'Shipping Method chosen',
                    'type' => 'varchar',
                    'length' => 255,
                    'not null' => FALSE,
                ),
                'tracking_number' => array(
                    'description' => 'Tracking number for the shipments',
                    'type' => 'varchar',
                    'length' => 255,
                    'not null' => FALSE,
                ),
            ),
            'primary key' => array('shipment_id'),
        );
          return $schema;
        }
