<?php
/**
 * @return array
 *
 * implements hook hook_menu()
 * builds the menu tabs for the site, both in the admin bar and in the page overlay.
 *
 */
function commerce_fulfillment_menu() {
  $items = array();

  //Creates the commerce fulfillment link
  $items['admin/commerce/orders/%commerce_order/commerce_fulfillment'] = array(
    'title' => t('Fulfillment'),
    'page callback' => 'commerce_fulfillment_package_content',
    'page arguments' => array(3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  // Creates the admin option link under the fulfillment tab
  $items['admin/commerce/orders/%commerce_order/commerce_fulfillment/admin'] = array(
    'title'=> t('Admin Options'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_fulfillment_admin_form', 3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'access callback' => true,
    'type' => MENU_LOCAL_TASK,
    'weight' => 51,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  //creates link to the package page
  $items['admin/commerce/orders/%commerce_order/commerce_fulfillment/orders'] = array(
    'title' => t('Packages'),
    'page callback' => 'commerce_fulfillment_package_content',
    'page arguments' => array(3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => -7,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  //Creates link to the shipment page.
  $items['admin/commerce/orders/%commerce_order/commerce_fulfillment/shipments'] = array(
    'title' => t('Shipments'),
    'page callback' => 'commerce_fulfillment_shipment_content',
    'page arguments' => array(3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  //Menu item for shipping label
  $items['shipping_label/%'] = array(
    'title' => t('Shipping Label'),
    'page callback' => 'commerce_fulfillment_shipping_label_view',
    'page arguments' => array(1),
    'access callback' => true,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  //Menu item for packing slip
  $items['packing_slip/%'] = array(
    'title' => t('Packing Slip'),
    'page callback' => 'commerce_fulfillment_packing_slip_view',
    'page arguments' => array(1),
    'access callback' => true,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_fulfillment.admin.inc',
    'file path' => drupal_get_path('module', 'commerce_fulfillment') . '/includes',
  );

  return $items;
}

/**
 * @return array
 * implements hook_views_api
 */
function commerce_fulfillment_views_api() {
  return array('api' => 3.0);
}

/**
 * @return mixed
 * implements hook_views_default_views
 */
function commerce_fulfillment_views_default_views() {

  $files = file_scan_directory(drupal_get_path('module', 'commerce_fulfillment') . '/views', '/.*\.inc$/');

  foreach ($files as $filepath => $file) {
    include $filepath;
    if(isset($view)) {
      $views[$view->name] = $view;
    }
  }

  return $views;
}

/**
 * Implements hook_entity_info()
 * Tells the Drupal API about our custom entities.
 */
function commerce_fulfillment_entity_info(){
  $info = array();

  $info['commerce_fulfillment_package'] = array(
    'label' => t('Commerce Fulfillment Package'),
    'base table' => 'commerce_fulfillment_packages',
    'entity keys' => array(
      'id' => 'package_id'
    ),
    'entity class'=> 'packageEntity',
    'controller class' =>'packageEntityController',
    'fieldable' => true,
    'module'=>'commerce_fulfillment',
  );

  $info['commerce_fulfillment_shipment'] = array(
    'label' => t('Commerce Fulfillment Shipment'),
    'base table' => 'commerce_fulfillment_shipments',
    'entity keys' => array(
      'id' => 'shipment_id',
    ),
    'entity class'=> 'shipmentEntity',
    'controller class' =>'shipmentEntityController',
    'fieldable' => true,
    'module'=>'commerce_fulfillment',
  );

  return $info;

}
/**
 * Implement hook_enable()
 */
function commerce_fulfillment_enable() {
  commerce_fulfillment_configure_package_type();
  commerce_fulfillment_configure_shipment_type();
}

/**
 * @param $type
 *
 * Ensures the line item field is present on the default order bundle.
 */
function commerce_fulfillment_configure_package_type($type = 'commerce_fulfillment_package') {

  // Look for or add a line item reference field to the order type.
  $field_name = 'commerce_fulfillment_line_items';
  commerce_activate_field($field_name);
  field_cache_clear();

  $field = field_info_field($field_name);
  $instance = field_info_instance('commerce_fulfillment_package', $field_name, $type);

  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'commerce_line_item_reference',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_types' => array('commerce_fulfillment_package'),
      'translatable' => FALSE,
      'locked' => TRUE,
    );
    field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'commerce_fulfillment_package',
      'bundle' => $type,
      'label' => t('Line items'),
      'settings' => array(),
      'widget' => array(
        'type' => 'commerce_line_item_manager',
        'weight' => -10,
      ),
      'display' => array(),
    );

    // Set the default display formatters for various view modes.
    foreach (array('default', 'customer', 'administrator') as $view_mode) {
      $instance['display'][$view_mode] = array(
        'label' => 'hidden',
        'type' => 'commerce_line_item_reference_view',
        'weight' => -10,
      );
    }

    field_create_instance($instance);
  }

  $field_name = 'commerce_fulfillment_shipping';

  field_cache_clear();

  $field = field_info_field($field_name);
  $instance = field_info_instance('commerce_fulfillment_package', $field_name, $type);
  //creates the package shipping info field
  if(empty($field)) {
    $field = array(
      'field_name' => 'commerce_fulfillment_shipping',
      'type' => 'text',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_types' => array('commerce_fulfillment_package', 'commerce_fulfillment_shipment'),
      'translatable' => TRUE,
    );

    field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'commerce_fulfillment_package',
      'bundle' => $type,
      'label' => t('Shipping Info'),
      'display' => array(),
    );

    field_create_instance($instance);
  }
}

/**
 * @param $type
 *
 * Ensures the line item field is present on the default order bundle.
 */
function commerce_fulfillment_configure_shipment_type($type = 'commerce_fulfillment_shipment') {

  // Look for or add a line item reference field to the order type.
  $field_name = 'commerce_fulfillment_packages';

  field_cache_clear();

  $field = field_info_field($field_name);
  $instance = field_info_instance('commerce_fulfillment_shipment', $field_name, $type);

  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'entityreference',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_types' => array('commerce_fulfillment_shipment'),
      'settings' => array(
        'target_type' => 'commerce_fulfillment_package',
        'handler_settings' => array('target_bundles'=> NULL),
      ),
      'translatable' => FALSE,
      'locked' => TRUE,
    );
    field_create_field($field);
  }

  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'commerce_fulfillment_shipment',
      'bundle' => $type,
      'label' => t('Packages'),
      'settings' => array(
        'target_type' => 'commerce_fulfillment_package',
        'handler_settings' => array('target_bundles'=> NULL),
      ),
      'display' => array(),
    );

    // Set the default display formatters for various view modes.
    foreach (array('default', 'customer', 'administrator') as $view_mode) {
      $instance['display'][$view_mode] = array(
        'label' => 'hidden',
        'type' => 'commerce_line_item_reference_view',
        'weight' => -10,
      );
    }

    field_create_instance($instance);
  }

  $field_name = 'commerce_fulfillment_shipping';

  field_cache_clear();

  $field = field_info_field($field_name);
  $instance = field_info_instance('commerce_fulfillment_shipment', $field_name, $type);
  //creates the package shipping info field
  if(empty($field)) {
    $field = array(
      'field_name' => 'commerce_fulfillment_shipping',
      'type' => 'text',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_types' => array('commerce_fulfillment_package', 'commerce_fulfillment_shipment'),
      'translatable' => TRUE,
    );

    field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'commerce_fulfillment_shipment',
      'bundle' => $type,
      'label' => t('Shipping Info'),
      'display' => array(),
    );

    field_create_instance($instance);
  }
}

/**
 * @return array
 *
 * Implements hook_theme()
 */
function commerce_fulfillment_theme() {
  return array(
    'packing_slip' => array(
      'template' => 'templates/commerce_fulfillment--packing_slip',
    ),
    'shipping_label' => array(
      'template' => 'templates/commerce_fulfillment--shipping_label'
    ),
  );
}

/**
 * @return array
 *
 * Implements hook_action_info()
 * Creates custom Views Bulk Operations
 */
function commerce_fulfillment_action_info(){
  return array(
    'commerce_fulfillment_add_product_action' => array(
      'type' => 'entity',
      'label' => t('Add Product to Package'),
      'behaviour' => array('changes_property'),
      'configurable' => TRUE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
      'aggregate' => TRUE,
    ),
    'commerce_fulfillment_remove_product_action' => array(
      'type' => 'entity',
      'label' => t('Remove Product from Package'),
      'behaviour' => array('changes_property'),
      'configurable' => TRUE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
      'aggregate' => TRUE,
    ),
    'commerce_fulfillment_add_package_action' => array(
      'type' => 'entity',
      'label' => t('Add Package to Shipment'),
      'behaviour' => array('changes_property'),
      'configurable' => TRUE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
      'aggregate' => TRUE,
    ),
    'commerce_fulfillment_remove_package_action' => array(
      'type' => 'entity',
      'label' => t('Remove Package from Shipment'),
      'behaviour' => array('changes_property'),
      'configurable' => TRUE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
      'aggregate' => TRUE,
    ),
  );
}

/**
 * @param $object
 * @param array $context
 *
 * Logic behind adding a product to a package.
 */
function commerce_fulfillment_add_product_action(&$object, $context = array()){
  $package_index = $context['package'];
  $order_id = $context ['order_id'];
  $package = commerce_fulfillment_get_array($order_id, $package_index, 'package_in_order');
  $package_entity = entity_load('commerce_fulfillment_package', false, array('package_id' => $package));
  $package_wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $package_entity[$package]);

  foreach ($object as $line_item) {
    $count = 0;

    foreach ($package_wrapper->commerce_fulfillment_line_items->value() as $index) {

      if ($index->line_item_id == $line_item->line_item_id) {
        drupal_set_message(t('Product @product_id already in Package @package', array('@product_id' => $line_item->line_item_id, '@package' => $package)),'error');
        $count++;
      }
    }

    if($count == 0){
      $package_wrapper->commerce_fulfillment_line_items[] = $line_item->line_item_id;
    }
  }
  $package_wrapper->save();
}

/**
 * @param $options
 * @return array
 *
 * Implements hook_form
 * Creates the form for adding products to packages
 *
 */
function commerce_fulfillment_add_product_action_form($options){
  $order_id = $options['view']->args[0];

  $form = array();

  $form['commerce_fulfillment_package'] = array(
    '#type' => 'select',
    '#title' => t('Select a Package:'),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'package_in_order'),
    '#required' => true,
  );
  $form['commerce_fulfillment_order'] = array(
    '#type' => 'hidden',
    '#value' => $order_id
  );
  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 *
 * Implements hook submit
 *
 */
function commerce_fulfillment_add_product_action_submit($form, &$form_state){
  $output['package'] = $form_state['values']['commerce_fulfillment_package'];
  $output['order_id'] = $form_state['values']['commerce_fulfillment_order'];
  return $output;
}

/**
 * @param $object
 * @param array $context
 *
 * Logic behind removing a product from a package
 *
 */
function commerce_fulfillment_remove_product_action(&$object, $context = array()){
  $max = 0;
  $index_array = array();

  $package_id = $context['package_id'];
  $package_entity = entity_load('commerce_fulfillment_package', false, array('package_id' => $package_id));

  $package_wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $package_entity[$package_id]);

  foreach ($package_wrapper->commerce_fulfillment_line_items->value() as $index) {

    foreach ($object as $line_item) {

      if ($index->line_item_id == $line_item->line_item_id) {
        $index_array[] = $max;
      }
    }
    $max++;
  }

  foreach ($index_array as $index) {
    unset($package_wrapper->commerce_fulfillment_line_items[$index]);
    $package_wrapper->save();
  }

}

/**
 * @param $options
 * @return array
 *
 * Implements hook_form
 * Creates the form for removing products from a package
 *
 */
function commerce_fulfillment_remove_product_action_form($options){
  $order_id = $options['view']->args[0];

  $form = array();

  $form['commerce_fulfillment_package_id'] = array(
    '#type' => 'select',
    '#title' => t('Select a Package:'),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'package_in_order'),
    '#required' => true,
  );
  $form['commerce_fulfillment_order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id
  );
  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 *
 * Implements hook_submit
 */
function commerce_fulfillment_remove_product_action_submit($form, &$form_state){
  $output['package_id'] = commerce_fulfillment_get_array($form_state['values']['commerce_fulfillment_order_id'], $form_state['values']['commerce_fulfillment_package_id'], 'package_in_order');
  return $output;
}

/**
 * @param $object
 * @param array $context
 *
 * Logic behind adding a product to a package.
 */
function commerce_fulfillment_add_package_action(&$object, $context = array()){
  $shipment_index = $context['shipment'];
  $order_id = $context ['order_id'];
  $shipment = commerce_fulfillment_get_array($order_id, $shipment_index, 'shipment_in_order');
  $shipment_entity = entity_load('commerce_fulfillment_shipment', false, array('shipment_id' => $shipment));
  $shipment_wrapper = entity_metadata_wrapper('commerce_fulfillment_shipment', $shipment_entity[$shipment]);

  foreach ($object as $package) {
    $count = 0;

    foreach ($shipment_wrapper->commerce_fulfillment_packages->value() as $index) {

      if ($index->package_id == $package->package_id) {
        drupal_set_message(t('Package @package_id already in Shipment @shipment', array('@package_id' => $package->package_id, '@shipment' => $shipment)),'error');
        $count++;
      }
    }

    if($count == 0){
      $shipment_wrapper->commerce_fulfillment_packages[] = $package->package_id;
    }
  }
  $shipment_wrapper->save();
}

/**
 * @param $options
 * @return array
 *
 * Implements hook_form
 * Creates the form for adding products to packages
 *
 */
function commerce_fulfillment_add_package_action_form($options){
  $order_id = $options['view']->args[0];

  $form = array();

  $form['commerce_fulfillment_shipment'] = array(
    '#type' => 'select',
    '#title' => t('Select a Shipment:'),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'shipment_in_order'),
    '#required' => true,
  );
  $form['commerce_fulfillment_order'] = array(
    '#type' => 'hidden',
    '#value' => $order_id
  );
  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 *
 * Implements hook submit
 *
 */
function commerce_fulfillment_add_package_action_submit($form, &$form_state){
  $output['shipment'] = $form_state['values']['commerce_fulfillment_shipment'];
  $output['order_id'] = $form_state['values']['commerce_fulfillment_order'];
  return $output;
}

/**
 * @param $object
 * @param array $context
 *
 * Logic behind removing a product from a package
 *
 */
function commerce_fulfillment_remove_package_action(&$object, $context = array()){
  $max = 0;
  $index_array = array();
  $shipment_id = $context['shipment_id'];
  $shipment_entity = entity_load('commerce_fulfillment_shipment', false, array('shipment_id' => $shipment_id));

  $shipment_wrapper = entity_metadata_wrapper('commerce_fulfillment_shipment', $shipment_entity[$shipment_id]);

  foreach ($shipment_wrapper->commerce_fulfillment_packages->value() as $index) {

    foreach ($object as $package) {

      if ($index->package_id == $package->package_id) {
        $index_array[] = $max;
      }
    }
    $max++;
  }

  foreach ($index_array as $index) {
    unset($shipment_wrapper->commerce_fulfillment_packages[$index]);
    $shipment_wrapper->save();
  }
}

/**
 * @param $options
 * @return array
 *
 * Implements hook_form
 * Creates the form for removing products from a package
 *
 */
function commerce_fulfillment_remove_package_action_form($options){
  $order_id = $options['view']->args[0];

  $form = array();

  $form['commerce_fulfillment_shipment_id'] = array(
    '#type' => 'select',
    '#title' => t('Select a Shipment:'),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'shipment_in_order'),
    '#required' => true,
  );
  $form['commerce_fulfillment_order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id
  );
  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 *
 * Implements hook_submit
 */
function commerce_fulfillment_remove_package_action_submit($form, &$form_state){
  $output['shipment_id'] = commerce_fulfillment_get_array($form_state['values']['commerce_fulfillment_order_id'], $form_state['values']['commerce_fulfillment_shipment_id'], 'shipment_in_order');
  return $output;
}

/**
 * @param $form_id
 * @param $args
 * @return array
 *
 * implements hook_forms
 * Allows for multiple forms to be applied to each page, each with their separate id and submit button.
 */
function commerce_fulfillment_forms($form_id, $args){
  $forms = array();

  if (strpos($form_id, 'commerce_fulfillment_manipulate_package_form_') !== FALSE) {
    $forms[$form_id] = array(
      'callback' => 'commerce_fulfillment_manipulate_package_form_builder',
      'callback arguments' => $args,
    );
  }

  if (strpos($form_id, 'commerce_fulfillment_manipulate_shipment_form_') !== FALSE) {
    $forms[$form_id] = array(
      'callback' => 'commerce_fulfillment_manipulate_shipment_form_builder',
      'callback arguments' => $args,
    );
  }

  return $forms;
}

/**
 * @param $form
 * @param $form_state
 * @return array
 *
 * implements hook hook_form
 * Adds the select box and add button to the packages interface.
 */
function commerce_fulfillment_manipulate_package_form_builder($form, &$form_state, $args){
  $package_id = $args[0];
  $order_id = $args[1];
  $form = array();
  $options = array(0 => t('Add Product'), 1 => t('Remove Product'), 2 => t('Delete Package'));

  $form['commerce_fulfillment_package_id'] = array(
    '#type' => 'hidden',
    '#value' => $package_id,
  );
  $form['commerce_fulfillment_order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id,
  );
  $form['commerce_fulfillment_product'] = array(
    '#type' => 'select',
    '#title' => t('Select Product to Add: '),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'commerce_order'),
  );
  $form['commerce_fulfillment_radios'] = array(
    '#type' => 'radios',
    '#title' => t('Options'),
    '#default_value' => $options[0],
    '#options' => $options
  );
  $form['commerce_fulfillment_add'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  $form['#submit'][] = 'commerce_fulfillment_manipulate_entity_form_submit';

  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @param $args
 * @return array
 *
 * implements hook hook_form
 * Adds the select box and add button to the packages interface.
 */
function commerce_fulfillment_manipulate_shipment_form_builder($form, &$form_state, $args){
  $options = array(0 => t('Add Package'),1 => t('Remove Package'), 2 => t('Delete Shipment'));
  $shipment_id = $args[0];
  $shipment = entity_load('commerce_fulfillment_shipment', FALSE, array('shipment_id'=>$shipment_id));

  $order_id = $shipment[$shipment_id]->order_id;

  $form['commerce_fulfillment_order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id,
  );
  $form['commerce_fulfillment_shipment_id'] = array(
    '#type' => 'hidden',
    '#value' => $shipment_id,
  );
  $form['commerce_fulfillment_package'] = array(
    '#type' => 'select',
    '#title' => t('Select Package: '),
    '#options' => commerce_fulfillment_get_array($order_id, 'false', 'package_in_order'),
  );
  $form['commerce_fulfillment_radios'] = array(
    '#type' => 'radios',
    '#title'=>t('Options'),
    '#default_value' => $options[0],
    '#options' => $options
  );
  $form['commerce_fulfillment_add'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['#submit'][] = 'commerce_fulfillment_manipulate_entity_form_submit';

  return $form;
}

function commerce_fulfillment_manipulate_entity_form_submit($form, &$form_state) {

  if (isset($form_state['values']['commerce_fulfillment_shipment_id'])) {

    //loads shipment
    $shipment_id = $form_state['values']['commerce_fulfillment_shipment_id'];
    $shipment = entity_load('commerce_fulfillment_shipment', FALSE, array('shipment_id' => $shipment_id));

    //gets the argument to add/remove from the shipment
    $argument = commerce_fulfillment_get_array($form_state['values']['commerce_fulfillment_order_id'], $form_state['values']['commerce_fulfillment_package'], 'package_in_order');

    //sets the wrapper and field variable to what we need if we are manipulating a shipment
    $wrapper = entity_metadata_wrapper('commerce_fulfillment_shipment', $shipment[$shipment_id]);
    $field = 'commerce_fulfillment_packages';
    $type2 = 'Shipment';
    $id = $shipment_id;
    $type1 = 'Package';

    //checks if there is a package with the argument ID
    $p_array = $wrapper->commerce_fulfillment_packages->value();
  }
  else {

    //loads the package entity
    $order_id = $form_state['values']['commerce_fulfillment_order_id'];
    $package_id[0] = $form_state['values']['commerce_fulfillment_package_id'];
    $package = entity_load('commerce_fulfillment_package', $package_id, array('order_id' => $order_id));

    //sets the wrapper and field variable to what we need if we are manipulating a shipment
    $wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $package[$package_id[0]]);
    $field = 'commerce_fulfillment_line_items';
    $type2 = 'Package';
    $id = $package_id[0];
    $type1 = 'Product';

    //creates an array of line_items in the specific package.
    $p_array = array();
    foreach ($wrapper->commerce_fulfillment_line_items->value() as $line_item) {
      $p_array[] = $line_item;
    }

    $argument = commerce_fulfillment_get_array($order_id, $form_state['values']['commerce_fulfillment_product'], 'commerce_order');

  }

  //add a product to a package
  if ($form_state['values']['commerce_fulfillment_radios'] == 0) {
    $count = 0;
    if (isset($p_array)) {

      foreach ($p_array as $p_id) {

        if (isset($p_id->type)) {
          $line_item = entity_metadata_wrapper('commerce_line_item', $p_id);
          $p_id = $line_item->line_item_id->value();
        }
        else{
          $package = entity_metadata_wrapper('commerce_fulfillment_package', $p_id);
          $p_id = $package->package_id->value();
        }
        if($p_id == $argument){
          $count++;
          drupal_set_message(t('@type1 @argument is already in @type2 @id.', array('@type1' => $type1, '@type2' => $type2, '@argument' => $argument, '@id' => $id)), 'error');
        }
      }
    }

    if ($count == 0) {
      if(isset($wrapper->{$field}->value()[0])){
        if($type2 == 'Shipment'){
          $id2 = $argument;
          $argument = entity_load('commerce_fulfillment_package', FALSE, array('package_id' => $argument));
          $argument_wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $argument[$id2]);
          $argument = $argument[$argument_wrapper->package_id->value()];
        }
        $wrapper->{$field}[] = $argument;
      }
      else{

        if($type2 == 'Shipment'){
          $id2 = $argument;
          $argument = entity_load('commerce_fulfillment_package', FALSE, array('package_id' => $argument));
          $argument_wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $argument[$id2]);
          $argument = $argument[$argument_wrapper->package_id->value()];
        }
        $wrapper->{$field}[] = $argument;
      }

      $wrapper->save();
    }
  }
  //remove a product from a package
  elseif($form_state['values']['commerce_fulfillment_radios'] == 1) {
    $count = 0;
    $success_count = 0;

    foreach ($p_array as $index) {

      if(isset($index->type)) {
        $line_item = entity_metadata_wrapper('commerce_line_item', $index);
        $index = $line_item->line_item_id->value();
        $type1 = 'Product';
      }
      else{
        $package_wrapper = entity_metadata_wrapper('commerce_fulfillment_package', $index);
        $index = $package_wrapper->package_id->value();
        $id = $shipment_id;
        $type1 = 'Package';
      }

      if ($index == $argument) {
        unset($wrapper->{$field}[$count]);
        $wrapper->save();
        drupal_set_message(t('@type1 @argument deleted from @type2 @id.', array('@type1' => $type1, '@type2' => $type2, '@argument' => $argument, '@id' => $id)));
        $success_count++;
      }
      $count++;
    }

    if($success_count == 0){

      drupal_set_message(t('@type1 @argument not found in @type2 @id.', array('@type1' => $type1, '@type2' => $type2, '@argument' => $argument, '@id' => $id)));
    }
  }
  //delete entity
  elseif($form_state['values']['commerce_fulfillment_radios']==2){
    $wrapper->delete();
    drupal_set_message(t('@type2 @id deleted.', array('@type2' => $type2, '@id' => $id)));
  }
}

/**
 * @param $order_id
 * @param $index
 * @param $type
 * @return array
 *
 * Creates an array of the necessary id type.
 * If there was an index chosen, returns the value of that index.
 * Otherwise just returns the array.
 */
function commerce_fulfillment_get_array($order_id, $index = 'false', $type){
  //@TODO - Turn this into a switch
  $id_array = array();
  //creates an array of products in a commerce order. Returns selected product if one chosen.
  if($type == 'commerce_order'){
    $entity_array = array();
    $entity_array[] = commerce_order_load($order_id);
  }
  //creates an array of products in a commerce order. Returns selected product if one chosen.
  elseif($type == 'package_in_order'){
    $entity_array = entity_load('commerce_fulfillment_package', FALSE, array('order_id' => $order_id));


    foreach($entity_array as $entity){
      $entity = entity_metadata_wrapper('commerce_fulfillment_package', $entity);
      $id_array[] = $entity->package_id->value();
    }
    if($index == 'false') {
      return $id_array;
    }
    return $id_array[$index];
  }
  elseif($type == 'shipment_in_order'){
    $entity_array = entity_load('commerce_fulfillment_shipment', FALSE, array('order_id' => $order_id));
    foreach($entity_array as $entity){
      $entity = entity_metadata_wrapper('commerce_fulfillment_shipment', $entity);
      $id_array[] = $entity->shipment_id->value();
    }
    if($index == 'false') {
      return $id_array;
    }
    else {
      return $id_array[$index];
    }
  }
  else {
    $entity_array = entity_load($type, FALSE, array('order_id' => $order_id));
  }

  foreach ($entity_array as $entity) {
    $entity = entity_metadata_wrapper($type, $entity);

    if (isset($entity->commerce_line_items)) {

      foreach ($entity->commerce_line_items->value() as $line_item) {
        $id_array[] = $line_item->line_item_id;
      }
    }
    elseif (isset($entity->commerce_fulfillment_line_items)) {

      foreach ($entity->commerce_fulfillment_line_items->value() as $line_item) {
        $id_array[] = $line_item->line_item_id;
      }
    }
  }

  if ($index == 'false') {
    return $id_array;
  }
  return $id_array[$index];

}
class shipmentEntityController extends EntityAPIController{
}

class shipmentEntity extends Entity{
}

class packageEntityController extends EntityAPIController{
}

class packageEntity extends Entity{
}
