<?php
/**
 * @return array
 *
 * implements hook hook_menu()
 * builds the menu tabs for the site, both in the admin bar and in the page overlay.
 *
 */
function commerce_fulfilment_menu() {
    $items = array();

    /**
     * Creates the commerce fulfilment link
     */
    $items['admin/commerce/manage-orders/commerce_fulfilment'] = array(
        'title' => t('commerce_fulfilment'),
        'description' => t('A custom menu'),
        'page callback' => 'orders_content',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => true,
        'weight' => 50
    );

    /**
     * creates link to the package page
     */
    $items['admin/manage-orders/%commerce_order/orders'] = array(
        'title' => 'Edit',
        'page callback' => 'orders_content',
        'page arguments' => array(2),
        'access callback' => 'commerce_order_access',
        'access arguments' => array('update', 2),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => -7,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    );

    /**
     * Creates link to the shipment page.
     */
    $items['admin/commerce/manage-orders/commerce_fulfilment/shipments'] = array(
        'title' => t('Shipments'),
        'description' => t('Shipments tab'),
        'page callback' => 'shipments_content',
        'type' => MENU_LOCAL_TASK,
        'access callback' => true,
        'weight' => 1
    );


    return $items;
}

/**
 * @param $order
 * @return string
 *
 * Builds the package page.
 */
function orders_content($order) {
    dpm($order);
    $output = 'Hello World';
    return $output;
}

/**
 * @return string
 *
 * Builds the shipments page
 *
 */
function shipments_content() {
    return '<h2>'.t('Shipments info').'</h2>';
}

/**
 * @return array
 * implements hook hook_admin_paths()
 * allows us to us the admin bar.
 */
function commerce_fulfilment_admin_paths() {
    $paths = array(
        'commerce/manage-orders/commerce_fulfilment/*/add' => TRUE,
        'commerce/manage-orders/commerce_fulfilment/*/edit' => TRUE,
    );
    return $paths;
}

/**
 * @return array
 * implement hook hook_overlay_paths()
 *
 */
function commerce_fulfilment_overlay_paths() {
    $paths = array(
        'commerce/manage-orders/commerce_fulfilment/*/add' => TRUE,
        'commerce/manage-orders/commerce_fulfilment/*/edit' => array(
            'width' => 500,
        ),
    );
    return $paths;
}
