<?php
/***********************************************************************************
 * This file is part of Commerce Fulfilment. A drupal module used to fulfil        *
 * orders placed in the Drupal Commerce module.                                    *
 *                                                                                 *
 * Authors: Dylan Harvey, Evan Schisler, Levi Weir, Parker Groenewoud              *
 *                                                                                 *
 * Project for COSC224 - Projects in Computer Science at Okanagan College.         *
 * Sponsored by AcroMedia                                                          *
 *                                                                                 *
 *                                                                                 *
 * Version: 1.0 - 12/03/15 - (Code before header)                                  *
 *          1.1 - 26/03/15 - (Code after header)                                   *
 *          1.2 - 06/04/15a - (Added implementation for packages.)                 *
 *          1.3 - 07/04/15 - (Product into package functional. One bug with forms) *
 *          1.4 - 07/04/15 - (Menu tabs fixed, unnecessary code removed)           *
 *          1.5 - 08/04/15 - (Fixed the multiple forms bug)                        *
 *          1.6 - 09/04/15 - Added implementation for shipments.                   *
 *          1.7 - 09/04/15 - Added ability to remove products and packages         *
 *                              and delete packages and shipment                   *
 *	    1.8 - 10/04/15 - Implemented view for orders in packages page	   *
 * Originially from: http://choosealicense.com/licenses/mit/                       *
 * The MIT License (MIT)                                                           *
 *                                                                                 *
 *                                                                                 *
 *                                                                                 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy    *
 * of this software and associated documentation files (the "Software"), to deal   *
 * in the Software without restriction, including without limitation the rights    *
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       *
 * copies of the Software, and to permit persons to whom the Software is           *
 * furnished to do so, subject to the following conditions:                        *
 *                                                                                 *
 * The above copyright notice and this permission notice shall be included in all  *
 * copies or substantial portions of the Software.                                 *
 *                                                                                 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      *
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        *
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     *
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          *
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   *
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   *
 * SOFTWARE.                                                                       *
 **********************************************************************************/
/**
 * @return array
 *
 * implements hook hook_menu()
 * builds the menu tabs for the site, both in the admin bar and in the page overlay.
 *
 */
function commerce_fulfilment_menu() {
    $items = array();

    /**
     * Creates the commerce fulfilment link
     */
    $items['admin/commerce/orders/%commerce_order/commerce_fulfilment'] = array(
        'title' => 'Fulfilment',
        'page callback' => 'commerce_fulfilment_package_content',
        'page arguments' => array(3),
        'access callback' => 'commerce_order_access',
        'access arguments' => array('update', 3),
        'type' => MENU_LOCAL_TASK,
        'weight' => 50
    );
    $items['admin/commerce/orders/%commerce_order/commerce_fulfilment/admin'] = array(
        'title'=> 'Admin Options',
        'page callback' => 'commerce_fulfilment_admin_content',
        'page arguments' => array(3),
        'access callback' => 'commerce_order_access',
        'access arguments' => array('update', 3),
        'access callback' => true,
        'type' => MENU_LOCAL_TASK,
        'weight' => 51
    );
    /**
     * creates link to the package page
     */
    $items['admin/commerce/orders/%commerce_order/commerce_fulfilment/orders'] = array(
        'title' => 'Packages',
        'page callback' => 'commerce_fulfilment_package_content',
        'page arguments' => array(3),
        'access callback' => 'commerce_order_access',
        'access arguments' => array('update', 3),
        'type' => MENU_LOCAL_TASK,
        'weight' => -7,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    );

    /**
     * Creates link to the shipment page.
     */
    $items['admin/commerce/orders/%commerce_order/commerce_fulfilment/shipments'] = array(
        'title' => t('Shipments'),
        'page callback' => 'commerce_fulfilment_shipment_content',
        'page arguments' => array(3),
        'access callback' => 'commerce_order_access',
        'access arguments' => array('update', 3),
        'type' => MENU_LOCAL_TASK,
        'weight' => 0,
    );
    return $items;
}
/**
 * @return mixed
 * implements admin page.
 * prints admin form
 * Also shows menu tabs for navigation.
 */
function commerce_fulfilment_admin_content(){
    $output = '';
    $output .= drupal_render(drupal_get_form('commerce_fulfilment_admin_form'));
    return $output;
}
/**
 * @param $order
 * @return string
 *
 * Builds the package page.
 * Pulls in Order info and displays the name of the products in chosen Order.
 *
 */
function commerce_fulfilment_package_content($order)
{
    $type = 'package';
    $order_id = $order->order_id;
    //dpm($order);
    $line_id = $order->commerce_line_items['und'];
    dpm($line_id);
    $products = commerce_line_item_load_multiple($line_id);
    dpm($products);
    $packages = entity_load($type, FALSE, array('order_id'=>$order_id));
    //dpm($packages);
    $output = '<table><tr><td style = vertical-align:top>';
    $output .= '<h2>' . t('Products in Order ' .$order_id . ':') . '</h2>';
    $output .= views_embed_view('commerce_fulfilment_order', 'order_block', $order_id);
    $output .= '</td><td style = vertical-align:top><h2>Created Packages for This Order:</h2>';
    foreach ($packages as $package) {
        $package_id = $package->package_id;
        $output .= '<h3>Package ' . $package_id . ':</h3>';
        $output .= '<h4>Products in Package:</h4>';
        $line_items = $package->line_items;
        $line_items = commerce_line_item_load_multiple($line_items['und']);
        foreach($line_items as $lineitem){
            $output .= '<p><strong>Product ID: </strong>' . $lineitem->line_item_id . '</p><p><strong>Product Code: </strong>' . $lineitem->line_item_label . '</p>';
        }
        $output .= drupal_render(drupal_get_form('commerce_fulfilment_add_product_form_' . $package_id, array('0' => $package, '1' => $order)));
    }
    $output.='</td></tr></table>';
    $output .= drupal_render(drupal_get_form('commerce_fulfilment_create_package_form', $order));
    return $output;
}

/**
 * @param $form
 * @param $form_state
 * @param $order
 * @return array
 *
 * implements hook_form
 * adds functionality to create a package
 *
 */
function commerce_fulfilment_create_package_form($form, &$form_state,$order){
    //dpm($order);

    $form = array();
    $form['order'] = array(
        '#type' => 'hidden',
        '#value' => $order,
    );
    $form['title'] = array(
        '#markup'=>'<h2>Create a New Package:</h2>'
    );
    $form['box_type'] = array(
        '#type' => 'select',
        '#title' => 'Select box type: ',
        '#options' => array(variable_get("commerce_fulfilment_boxtype")),
        '#default_value' => 'default',
    );
    $form['create'] = array(
        '#type' => 'submit',
        '#value' => t('Create a Package')
    );
    return $form;
}

/**
 * @param $form
 * @param $form_state
 *
 * implements hook_form_submit
 */
function commerce_fulfilment_create_package_form_submit($form, &$form_state){
    $order = $form_state['values']['order'];
    $shippings = $order->commerce_customer_shipping['und'][0];
    $shipping = commerce_customer_profile_load($shippings);
    $entity_type = 'package';
    $entity = entity_create($entity_type, array(
        'order_id' => $order->order_id,
        'box_type' => $form_state['values']['box_type'],
        'shipping_info'=>array(
            'firstName' => substr($shipping->commerce_customer_address['und'][0]['first_name'], 0, 50),
            'lastName' => substr($shipping->commerce_customer_address['und'][0]['last_name'], 0, 50),
            'company' => substr($shipping->commerce_customer_address['und'][0]['organisation_name'], 0, 50),
            'address' => substr($shipping->commerce_customer_address['und'][0]['thoroughfare'], 0, 60),
            'city' => substr($shipping->commerce_customer_address['und'][0]['locality'], 0, 40),
            'state' => substr($shipping->commerce_customer_address['und'][0]['administrative_area'], 0, 40),
            'zip' => substr($shipping->commerce_customer_address['und'][0]['postal_code'], 0, 20),
            'country' => $shipping->commerce_customer_address['und'][0]['country'],
        ),
    ));
    $entity->save('package', $entity);
}
/**
 * @param $form_id
 * @param $args
 * @return array
 *
 * implements hook_forms
 * Allows for multiple forms to be applied to each page, each with their separate id and submit button.
 */
function commerce_fulfilment_forms($form_id, $args){
    $forms = array();
    if (substr($form_id, 0, 37) == 'commerce_fulfilment_add_product_form_') {
        $forms[$form_id] = array(
            'callback' => 'commerce_fulfilment_add_product_form_builder',
            'callback arguments' => $args,
        );
    }
    if (substr($form_id, 0, 37) == 'commerce_fulfilment_add_package_form_') {
        $forms[$form_id] = array(
            'callback' => 'commerce_fulfilment_add_package_form_builder',
            'callback arguments' => $args,
        );
    }
    return $forms;
}
/**
 * @param $form
 * @param $form_state
 * @param $package
 * @param $order
 * @return form
 *
 * implements hook hook_form
 * Adds the select box and add button to the packages interface.
 */
function commerce_fulfilment_add_product_form_builder($form, &$form_state, $args){
    $package = $args[0];
    $order = $args[1];
    $form = array();
    $options = array(0 => t('Add Product'),1 => t('Remove Product'), 2 => t('Delete Package'));
    $form['package'] = array(
        '#type' => 'hidden',
        '#value' => $package,
    );
    $form['order'] = array(
        '#type' => 'hidden',
        '#value' => $order,
    );
    $form['product'] = array(
        '#type' => 'select',
        '#title' => 'Select Product to Add: ',
        '#options' => commerce_fulfilment_get_product_array($order),
    );
    $form['radios'] = array(
        '#type' => 'radios',
        '#title'=>t('Options'),
        '#default value' => $options[0],
        '#options' => $options
    );
    $form['add'] = array(
        '#type' => 'submit',
        '#value' => t('Submit')
    );
    $form['#submit'][] = 'commerce_fulfilment_add_product_form_submit';
    return $form;
}
/**
 * loads an array of line item id's.
 * If there is no index chosen, Returns the array.
 * If there is an index chosen. Returns the data in the array at that index.
 */
function commerce_fulfilment_get_product_array($order, $index = FALSE)
{

    $line_ids = $order->commerce_line_items['und'];
    //dpm($line_ids);
    $line_id = array();
    $count = 0;
    /**
     * Creates an array of order product id's for the select box.
     */
    foreach ($line_ids as $id) {
        $line_id[$count] = $id['line_item_id'];
        $count++;
    }
    if($index !== FALSE && is_int($index) && $index <= count($line_ids))
    {
        return $line_id[$index];
    }
    return $line_id;
}
/**
 * @param $form
 * @param $formstate
 * implement hook hook_form_submit
 * Implements the functionality behind commerce_fulfilment_add_product_form
 *
 */
function commerce_fulfilment_add_product_form_submit($form, &$form_state)
{

    $package = $form_state['values']['package'];
    $order = $form_state['values']['order'];
    $products = $package->line_items['und'];
    $argument = commerce_fulfilment_get_product_array($order, (int)$form_state['values']['product']);
    if($form_state['values']['radios'] == 0) {
        $package->line_items['und'][] = $argument;
        $package->save('package', $package);
    }
    elseif($form_state['values']['radios'] == 1) {
        $count = 0;
        foreach ($products as $product) {
            if ($product == $argument) {
                $package->line_items['und'][$count] = NULL;
                $package->save('package', $package);
                $count++;
            }
        }
    }
    elseif($form_state['values']['radios']==2){
        $package->delete();
    }
}
/**
 * @return string
 *
 * Builds the shipments page
 *
 */
function commerce_fulfilment_shipment_content($order) {
    $order_id = $order->order_id;
    //dpm($order);
    $packages = entity_load('package', FALSE, array('order_id'=>$order_id));
    $packages_id = array();
    $shipments = entity_load('shipment', FALSE, array('order_num'=>$order_id));
    //dpm($packages);
    $output = '<table><tr>/table></td><td style = vertical-align:top><h2>Created Packages for This Order:</h2>';
    foreach ($packages as $package) {
        $package_id = $package->package_id;
        $packages_id[] = $package->package_id;
        $output .= '<h3>Package ' . $package_id . ':</h3>';
        $output .= '<h4>Products in Package:</h4>';
        $line_items = $package->line_items;
        $line_items = commerce_line_item_load_multiple($line_items['und']);
        foreach ($line_items as $lineitem) {
            $output .= '<p><strong>Product ID: </strong>' .$lineitem->line_item_id . '</p><p><strong>Product Code: </strong>' . $lineitem->line_item_label . '</p>';
        }
    }
    $output .= '</td><td style = vertical-align:top><h2>Created Packages for This Order:</h2>';
    foreach ($shipments as $shipment) {
        $shipment_id = $shipment->shipment_id;
        $output .= '<h3>Shipment ' . $shipment_id . ':</h3>';
        $output .= '<h4>Packages in Shipment:</h4>';
        $package_ids = $shipment->package_num['und'];
        dpm($package_ids);
        if($package_ids != NULL) {
            foreach ($package_ids as $packageid) {
                if ($packageid != NULL) {
                    $package = entity_load('package', FALSE, array('package_id' => $packageid));
                    $output .= '<p><strong>Package ID: </strong>' . (string)$package[1]->package_id . '</p><p><strong>Shipping Info: </strong>' . (string)$package[1]->shipping_info['address'] . '</p>';
                }
            }
        }
        $args = array();
        $args[] = $shipment;
        $args[] = $packages_id;
        $output .= drupal_render(drupal_get_form('commerce_fulfilment_add_package_form_' . $shipment_id, $args));
    }
    $output .= '</td></tr></table>';

    $output .= drupal_render(drupal_get_form('commerce_fulfilment_create_shipment_form', $order));

    return $output;
}
/**
 * @param $form
 * @param $form_state
 * @param $package
 * @param $order
 * @return form
 *
 * implements hook hook_form
 * Adds the select box and add button to the packages interface.
 */
function commerce_fulfilment_add_package_form_builder($form, &$form_state, $args)
{
    $options = array(0 => t('Add Package'),1 => t('Remove Package'), 2 => t('Delete Shipment'));
    $shipment = $args[0];
    $packages = $args[1];
    $package_arr = array();
    foreach ($packages as $package) {
        $package_arr[] = entity_load('package', FALSE, array('package_id' => $package));
    }
    $form['packages'] = array(
        '#type' => 'hidden',
        '#value' => $package_arr,
    );
    dpm($package_arr);
    $form['shipment'] = array(
        '#type' => 'hidden',
        '#value' => $shipment,
    );
    $form['package'] = array(
        '#type' => 'select',
        '#title' => 'Select Package: ',
        '#options' => $packages,
    );
    $form['radios'] = array(
      '#type' => 'radios',
        '#title'=>t('Options'),
        '#default value' => $options[0],
        '#options' => $options
    );
    $form['add'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    $form['#submit'][] = 'commerce_fulfilment_add_package_form_submit';
    return $form;
}

/**
 * @param $packages
 * @param bool $index
 * @return array
 * Gets an array of package_ids to display in the commerce_fulfilment_add_package_form_builder
 */
function commerce_fulfilment_get_package_array($packages, $index = FALSE){
    $package_id = array();
    $count = 0;
    /**
     * Creates an array of package id's for the select box.
     */
    foreach ($packages as $package) {
        $package_id[$count] = $package->package_id;
        $count++;
    }
    if($index !== FALSE && is_int($index) && $index <= count($package_id))
    {
        return $package_id[$index];
    }
    return $package_id;
}

/**
 * @param $form
 * @param $form_state
 *
 * Implements hook_form_submit,
 * Places a package into a shipment
 */
function commerce_fulfilment_add_package_form_submit(&$form, &$form_state){

    $shipment = $form_state['values']['shipment'];
    $package_arr = $form_state['values']['packages'];
    $package_ids = $shipment->package_num['und'];
    $value =  $shipment->package_num['und'][$package_arr[0][1 + (int)$form_state['values']['package']]];
    if($form_state['values']['radios']== 0 ) {
        $shipment->package_num['und'][] = $package_arr[0][1 + (int)$form_state['values']['package']]->package_id;
        $shipment->save('shipment', $shipment);
    }
    elseif($form_state['values']['radios'] == 1) {
        $count = 0;
        foreach ($package_ids as $package_id) {
            if ($package_id == $value) {
                $shipment->package_num['und'][$count] = NULL;
                $shipment->save('shipment', $shipment);
                $count++;
            }
        }
    }
    elseif($form_state['values']['radios']==2){
        $shipment->delete();
    }
}
/**
 * @param $form
 * @param $form_state
 * @param $order
 * @return array
 *
 * Implements hook_form
 * Implements form to create a new shipment object
 * Allows user to set the tracking number if desired
 *
 */

function commerce_fulfilment_create_shipment_form($form, &$form_state,$order){
    dpm($order);
    $form = array();
    $form['order'] = array(
        '#type' => 'hidden',
        '#value' => $order,
    );
    $form['title'] = array(
        '#markup'=>'<h2>Create a New Shipment:</h2>'
    );
    $form['tracking_number'] = array(
        '#type' => 'textfield',
        '#title' => 'Enter tracking number:',
        '#size' => 20,
        '#length' => 255,
        '#required' => false,
    );
    $form['create'] = array(
        '#type' => 'submit',
        '#value' => t('Create Shipment')
    );
    return $form;
}

function commerce_fulfilment_create_shipment_form_submit(&$form, &$form_state)
{
    $order = $form_state['values']['order'];
    $shippings = $order->commerce_customer_shipping['und'][0];
    $shipping = commerce_customer_profile_load($shippings);
    $entity_type = 'shipment';
    $entity = entity_create($entity_type, array(
        'order_num' => $order->order_id,
        'status' => 'pending',
        'packages' => '',
        'dates' => array(
            'created' => date(ymd),
        ),
        'method' => array(
            'method' => $order->commerce_order_total['und'][0]['data']['components'][1]['name'],
            'price' => $order->commerce_order_total['und'][0]['data']['components'][1]['price'],
        ),
        'shipping_info' => array(
            'firstName' => substr($shipping->commerce_customer_address['und'][0]['first_name'], 0, 50),
            'lastName' => substr($shipping->commerce_customer_address['und'][0]['last_name'], 0, 50),
            'company' => substr($shipping->commerce_customer_address['und'][0]['organisation_name'], 0, 50),
            'address' => substr($shipping->commerce_customer_address['und'][0]['thoroughfare'], 0, 60),
            'city' => substr($shipping->commerce_customer_address['und'][0]['locality'], 0, 40),
            'state' => substr($shipping->commerce_customer_address['und'][0]['administrative_area'], 0, 40),
            'zip' => substr($shipping->commerce_customer_address['und'][0]['postal_code'], 0, 20),
            'country' => $shipping->commerce_customer_address['und'][0]['country'],
        ),
        'tracking_number' => $form_state['values']['tracking_number'],
    ));
    $entity->save('shipment', $entity);
}
/**
 *
 * @return array
 * Implements hook_form
 * Creates an admin page form
 * Will use this data to print packing slips and shipping labels
 */
function commerce_fulfilment_admin_form(){
    $form = array();
    $form['title'] = array(
        '#markup' => '<h2>Admin Page</h2>'
    );
    /**
     * Creates seperate information fields
     */
    $form['Company Information']=array(
        '#type'=>'fieldset',
        '#title'=>t("Enter your company's information below"),
        '#description'=>'Enter information to use on Packing Slips and Shipping Labels.'
    );
    /**
     * Textfields
     */
    $form['Company Information']['company'] = array(
        '#type'=>'textfield',
        '#title'=>t('Company name:'),
    );
    $form['Company Information']['address'] = array(
        '#type'=>'textfield',
        '#title'=>t('Address:')
    );
    $form['Company Information']['phone'] = array(
        '#type'=>'textfield',
        '#title'=>t('Company Phone Number:')
    );
    $form['Company Information']['commerce_fulfilment_boxtype'] = array(
        '#type'=>'textfield',
        '#title'=>t('Add box size:'),
    );
    /**
     * Allows user to upload company logo
     */
    $form['#attributes']['enctype'] = 'multipart/form-data';

    $form['Company Information']['logo']=array(
        '#type'=>'file',
        '#title'=>t('Upload your company logo:'),
    );
    return system_settings_form($form);
}
/**
 * Implements hook hook_form_validate
 * Validates information entered into the form
 */
function commerce_fulfilment_admin_form_validate($form, &$form_state){
    if(empty($form_state['values']['company']))
        form_set_error('company','Company cannot be empty');
    if(empty($form_state['values']['address']))
        form_set_error('address','Address cannot be empty');
    if(empty($form_state['values']['phone']))
        form_set_error('phone','Phone cannot be empty');

    variable_set('commerce_fulfilment_boxtype',
        $form['commerce_fulfilment_boxtype']);

    variable_set('commerce_fulfilment_phone',
        $form['phone']);

    variable_set('commerce_fulfilment_address',
        $form['address']);

    variable_set('commerce_fulfilment_company',
        $form['company']);

    variable_set('commerce_fulfilment_logo',
        $form['logo']);
}

/**
 * @param $form
 * @param $form_state
 *
 * Allows the form to submit its information and display a message.
 *
 */
function commerce_fulfilment_admin_form_submit($form, &$form_state){
    drupal_set_message('Form has been submitted');
}

function commerce_fulfilment_views_api() {
  return array('api' => 3.0);
}

function commerce_fulfilment_views_default_views() {

  $files = file_scan_directory(drupal_get_path('module', 'commerce_fulfilment') . '/views', '/.*\.inc$/');

  foreach ($files as $filepath => $file) {
    require $filepath;
    if(isset($view)) {
      $views[$view->name] = $view;
    }
  }

  return $views;
  }

/**
 * Implements hook_entity_info()
 */
/////////////////Package Entity////////////////
function commerce_fulfilment_entity_info(){
    $info = array();
    $info['package'] = array(
        'label' => t('package'),
        'base table' => 'commerce_fulfilment_packages',
        'entity keys' => array(
            'id' => 'package_id'
        ),
        'entity class'=> 'packageEntity',
        'controller class' =>'packageEntityController',
        'fieldable' => true,
        'module'=>'commerce_fulfilment'
    );
    $info['shipment'] = array(
        'label' => t('shipment'),
        'base table' => 'commerce_fulfilment_shipments',
        'entity keys' => array(
            'id' => 'shipment_id',
        ),
        'entity class'=> 'shipmentEntity',
        'controller class' =>'shipmentEntityController',
        'fieldable' => true,
        'module'=>'commerce_fulfilment'
    );
    return $info;
}
class shipmentEntityController extends EntityAPIController{

}
class shipmentEntity extends Entity{

}
class packageEntityController extends EntityAPIController{

}
class packageEntity extends Entity{

}
