<?php
/**
 * Implements hook_schema().
 */
function commerce_fulfillment_schema() {

  $schema = array();

  $schema['commerce_fulfillment_packages'] = array(
    'description' => 'The base table for the package entity',
    'fields' => array(
      'package_id' => array(
        'description' => 'Primary key of the package entity',
        'type' => 'serial',
	'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'line_items' => array (
		'type' => 'varchar',
		'length' => '255',
		'not null' => TRUE,
	),
	'box_type' => array(
		'type' => 'varchar',
		'length' => '255',
		'not null' => FALSE,
	),
	'shipping_info' => array(
		'type' => 'varchar',
		'length' => '255',
		'not null' => TRUE,
	),
	'primary key' => array(package_id),
  ),
);

    $schema['commerce_fulfilment_shipments'] = array(
      'description' => 'The base table for the Shipment entity',
        'fields' => array(
            'shipment_id' => array(
                'description' => 'Primary key of the Shipment entity',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,

            ),
            'status' => array(
                'description' => 'Status of the shipment("Pending" or "Completed")',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
            ),
            'packages' => array(
                'description' => 'An array of the packages in the shipment.',
                'type' => 'int',
                'serialize' => TRUE,
                'not null' => FALSE,
            ),
            'date' => array(
                'description' => 'Date the shipment was shipped',
                'type' => 'int',
                'length' => 8,
                'not null' => FALSE,
            ),
        ),
        'primary key'=>'shipment_id',
    );

  return $schema;
}
